---
title: "exp-3"
output: html_document
date: "2025-10-13"
---

```{r}
library(MASS)
data(epil)
ndata=epil
ndata
```

```{r}
Y = ndata[,1]
hist(Y, breaks=40, freq=T)
```
```{r}
breaks=seq(min(Y)-0.5, max(Y)+0.5, by=1)
hist(Y, breaks = breaks, freq = FALSE, main = "PMF of Y")
```


```{r}
#1,
my=mean(Y)
mv=var(Y)
print(my)
print(mv)
```

```{r}
poismod=fitdistr(Y, densfun = "poisson")
lam=poismod$estimate
sprintf("Log Likehood:%f", poismod$loglik)
```

```{r}
k=0:max(Y)
pois_pmf = dpois(k,lambda = lam)
hist(Y, breaks = breaks, freq = FALSE, main = "PMF of Y")
lines(k,pois_pmf,lwd = 1, col = "red")
```


```{r}
# log likelihood[negative bino random variable]
nbmod=fitdistr(Y, densfun = "Negative Binomial")
nb_size=nbmod$estimate[1]
nb_mu=nbmod$estimate[2]
nb_pmf=dnbinom(k, size = nb_size, mu=nb_mu)
sprintf("Log Likelihood:%f", nbmod$loglik)
hist(Y, breaks = breaks, freq = FALSE, main = "PMF of Y")
lines(k, nb_pmf, lwd = 1, col = 'red')
```

```{r}
#split the data into test and train
nr=nrow(ndata)
s=sample(x=1:nr, size = 0.8*nr, replace = FALSE)
traindata=ndata[s,]
testdata=ndata[-s,]
linearmod=lm(y~lbase+lage+trt, data = traindata)
ypredtrain=predict(linearmod, traindata)
ypredtest=predict(linearmod, testdata)
```


